### ISSUE TITLE
Turn SlimerJS into an headless browser

### ISSUE THREAD

**Issue by laurentj** [laurentj/slimerjs#80] opened 2013-09-13 13:05 UTC
First solution : port [the patch of bug 446591](https://bugzilla.mozilla.org/show_bug.cgi?id=446591)  into XulRunner (so we need to compile and provide our own XulRunner). It will be a huge work.

Second solution: since Gecko 23, it seems there is a new method [nsIAppShellService::createWindowlessBrowser()](http://mxr.mozilla.org/mozilla-central/source/xpfe/appshell/public/nsIAppShellService.idl#47). We should investigate if we could use this method to load our webpages.

**Comment by rmsphd** [comment] 2015-04-18 16:03
:+1:

**Comment by andreasrosdal** [comment] 2015-04-25 09:16
:+1:

**Comment by nicolsondsouza** [comment] 2015-07-02 15:15
:+1:

**Comment by hadim** [comment] 2015-07-04 20:30
+1

**Comment by nicolai86** [comment] 2015-07-05 14:31
:+1:

**Comment by kidk** [comment] 2015-07-22 11:25
+1

**Comment by falconepl** [comment] 2015-09-05 17:23
:+1:

**Comment by abozhilov** [comment] 2015-09-06 16:26
@laurentj can you tell us more about the issues with `createWindowlessBrowser`. If there is no major issue or crashing xulrunner I think we can implement headless Slimer. My point is to use `createWindowlessBrowser` for creating chrome "wins" and then put XUL browser element for the actual page representation.

**Comment by ecLAllanon** [comment] 2015-12-04 07:19
:+1:

**Comment by tostercx** [comment] 2016-01-06 11:56
+1

**Comment by devanshah1** [comment] 2016-04-08 11:26
+1

**Comment by boyomarinov** [comment] 2016-04-22 14:12
+1

**Comment by laurentj** [comment] 2016-05-02 11:00
Please stop comments with "+1". Instead use the "add your reaction" (smiley) button above the issue description ;-) Thank you

**Comment by brendandahl** [comment] 2017-02-18 02:13
For those interested, I've started some work on this in https://bugzilla.mozilla.org/show_bug.cgi?id=1338004 . It's still in a very early stage, but I have a simple [slimer snapshot a page script](https://gist.github.com/brendandahl/6864ae09c46c54524b42d51583fac82e) working. Also, very early perf show's this shaving off around .1-.2s on this very simple script and I also see a [react benchmark](https://leeluolee.github.io/js-repaint-perfs/react/opt.html) go from ~24fps to 40fps. If anyone has some exceptionally slow slimer tests, I'd be curious to see them.

- Branch:
    https://github.com/brendandahl/gecko/tree/headless-slimerjs
- Linux 64 Build:
    https://queue.taskcluster.net/v1/task/W7FVxw9tQtWZqYAESasJtg/runs/0/artifacts/public/build/target.tar.bz2
- Use `MOZ_HEADLESS` environment variable e.g.:
    `DISPLAY=77 MOZ_HEADLESS=1 /home/bdahl/Downloads/firefox/firefox -app /home/bdahl/projects/slimerjs/src/application.ini -no-remote -profile /home/bdahl/projects/gecko/obj.debug.noindex/tmp/scratch_user slimer.js`

**Comment by laurentj** [comment] 2017-02-20 07:18
@brendandahl this is a very good news! However SlimerJS has some issues with Fx>52 and I cannot launch your test (even with an "official" nightly). I will fix this issue and I will test your build :-)

**Comment by laurentj** [comment] 2017-03-10 08:29
@brendandahl Awesome! It works with the latest release of SlimerJS, 0.10.3!! (after changing the max version to 54.* into application.ini)

```
export DISPLAY=77
export MOZ_HEADLESS=1
export SLIMERJSLAUNCHER=/home/laurent/tmp/fxheadless/firefox 
slimerjs test.js
```

**Comment by jefleponot** [comment] 2017-03-10 08:44
@laurentj ,

Just On question :+1: 
SlimerJS 0.10.3 is recommended to test Firefox between 38 to 54 -> ok

Which version do you recognize to test Firefox between 17 to 37 ?

**Comment by laurentj** [comment] 2017-03-10 08:47
@jefleponot SlimerJS 0.9.x

**Comment by laurentj** [comment] 2017-04-11 09:07
The latest nightlies of Firefox support the headless mode, even if there are some crashes with some unit tests of SlimerJS.

**Comment by jefleponot** [comment] 2017-04-11 09:22
HI @laurentj 
Thanks for news
Do you have a command line example ? 

Does that mean that SlimerJS will not be maintain anymore ? 

Thanks in advance

**Comment by laurentj** [comment] 2017-04-11 17:00
No more crashes with the build 2017-04-11 of Firefox nightly 55.0a1

**Comment by laurentj** [comment] 2017-04-11 17:02
@jefleponot 
>Do you have a command line example ?

see one of my latest comment here

>Does that mean that SlimerJS will not be maintain anymore ?

Why ??? Firefox does not have features of SlimerJS. But SlimerJS needs Firefox to run.

**Comment by brendandahl** [comment] 2017-04-11 19:05
Just to note, headless is currently only supported on Linux. If you want to follow along for other platforms see:
MacOS:
https://bugzilla.mozilla.org/show_bug.cgi?id=1355147
Windows:
https://bugzilla.mozilla.org/show_bug.cgi?id=1355150

**Comment by mykmelez** [comment] 2017-06-15 23:51
Note that Firefox 55 (currently in beta) will support headless browsing on Linux, per this announcement:
 
https://groups.google.com/forum/#!topic/firefox-dev/TEhvuBXcJCg

Beta builds are available from https://www.mozilla.org/en-US/firefox/channel/desktop/. As @brendandahl noted, Windows and macOS support is still in progress, and you can follow along on the bugs he references.

**Comment by puravida** [comment] 2017-06-16 00:24
Aside from the obvious resource savings of running headless, are there other benefits as well? Would this be more or less likely to crash (or properly load complex/problematic pages) than running a full instance? Are there other downsides to running Firefox headless? If this has all been discussed, ad naseum, before then please do point me there with a link. ;)

In the past, I spent more than 500 hours evaluating every available script, open source and paid, for capturing screenshots to use as a backup for my own, proprietary method. From that testing, I concluded that running headless had some serious issues with certain kinds of pages, such as pages that format based on viewport dimensions and such. The problem is that running headless meant there was no viewport dimensions reported, so some pages were crunched or had elements extending off the page (improper page height) or the backgrounds did not extend fully, etc. This is a major reason that CutyCapt, PhantomJS, and similar failed to meet my needs as a backup solution.

Lastly, has anyone run any metrics yet to judge the gains (less ram, less cpu) from running headless?

Just curious... Thanks!

**Comment by drasill** [comment] 2017-06-16 14:45
I don't know how it works on other platforms, but the major point on linux is that non-headless needs a Xorg server started, which is quite complicated on servers / docker instances.

**Comment by puravida** [comment] 2017-06-16 15:07
@drasill Thanks for the note. You are so right. Managing the "window manager" is one of my top headaches, and I would LOVE to eliminate that piece of the process. 

However, the viewport issues are too problematic, since I have to render ANY page as accurately as possible. I've captured screenshots of more than 500 million URLs (conservatively), and I think I've probably actually seen a million of them, haha! So, I know that the other headless methods were only good for specific use-cases where the web page(s) was/were known to be compatible.

However, as technology and methods advance, it would be GREAT to see a headless implementation that could overcome those limitations. :)

**Comment by mykmelez** [comment] 2017-06-16 16:47
> Aside from the obvious resource savings of running headless, are there other benefits as well? Would this be more or less likely to crash (or properly load complex/problematic pages) than running a full instance? Are there other downsides to running Firefox headless? If this has all been discussed, ad naseum, before then please do point me there with a link. ;)

I don't expect it to be less likely to crash, as it still exercises all of the rendering pipeline at the moment. However, future optimizations might avoid rendering and compositing (until you take a screenshot, anyway), which would reduce crashes in that code and improve performance. ([Out-of-process compositing](https://bugzilla.mozilla.org/show_bug.cgi?id=1264543) will also help with crashiness, for both headed and headless Firefox.)

Headless mode may also be more consistent, especially if you script Firefox on multiple platforms, since parts of the headless "widget backend" are cross-platform. A possible downside of that is that headless doesn't produce exactly the same results as headed with a platform-specific widget backend.

> The problem is that running headless meant there was no viewport dimensions reported, so some pages were crunched or had elements extending off the page (improper page height) or the backgrounds did not extend fully, etc. This is a major reason that CutyCapt, PhantomJS, and similar failed to meet my needs as a backup solution.

Headless mode for Firefox should report viewport dimensions (i.e. _window.innerWidth/innerHeight_) correctly for any window you open (or that SlimerJS opens for you). Screen dimensions are hardcoded to `1366x768`, per [HeadlessScreenHelper::GetScreenRect](http://searchfox.org/mozilla-central/rev/20d16dadd336e0c6b97e3e19dc4ff907744b5734/widget/headless/HeadlessScreenHelper.cpp#17-30), but can be configured at runtime via the _MOZ_HEADLESS_WIDTH_ and _MOZ_HEADLESS_HEIGHT_ environment variables.

**Comment by puravida** [comment] 2017-06-16 17:53
@mykmelez Nice. That is very insightful. Thank you.

> Headless mode for Firefox should report viewport dimensions (i.e. window.innerWidth/innerHeight) correctly for any window you open (or that SlimerJS opens for you). Screen dimensions are hardcoded to 1366x768, per HeadlessScreenHelper::GetScreenRect, but can be configured at runtime via the MOZ_HEADLESS_WIDTH and MOZ_HEADLESS_HEIGHT environment variables.

This would be awesome! Other scripts claimed to send the viewport, but really did not. If slimerjs could hook into the ability to adjust, like via MOZ_HEADLESS_XXX, then that would be a game-changer.

Thanks for the insight...

**Comment by mykmelez** [comment] 2017-08-16 23:31
Support for Windows and Mac has since landed in Firefox 56, which is currently in Beta.

@laurentj Is there anything to change in SlimerJS code to resolve this issue, or is it sufficient to document that you can run SlimerJS in headless mode on Firefox 56+ by specifying the right Firefox command-line flag/environment variable?

**Comment by birtles** [comment] 2017-08-21 23:20
I suppose at very least the `MaxVersion` in `application.ini` needs to be updated?

**Closed** 2017-10-13 10:26 UTC
Labels: Doc needed, enhancement

**Comment by brendanhowell** [comment] 2017-10-16 07:32
This is awesome! Will I be able to use my old scripts that render to PDF or is this only for PNG?
