### ISSUE TITLE
domWindowUtils.setCSSViewport is going away, stop using it

### ISSUE THREAD

**Issue by hallvors** [laurentj/slimerjs#402] opened 2015-11-19 22:34 UTC
In bug 1185747 Gecko killed the setCSSViewport function. SlimerJS calls it here:

https://github.com/laurentj/slimerjs/blob/0ebeb694693969d3cec178f1588a5f8872ce4776/src/modules/slimer-sdk/webpage.js#L861

Trying to run SlimerJS with Firefox 43 and greater causes this error:

Script Error: domWindowUtils.setCSSViewport is not a function
       Stack:
         -> resource://slimerjs/slimer-sdk/webpage.js: 861
         -> resource://slimerjs/slimer-sdk/webpage.js: 861 (in function _create/webpage.viewportSize)

I'm not quite sure why SlimerJS calls this method. Just commenting out that line seems to work to fix the problem.

**Comment by jadaradix** [comment] 2016-02-07 02:04
I reproduced this issue by copying /usr/lib/firefox to xulrunner in the linux SlimerJS distribution, jumping from 38 to 44 in platform.ini. Firefox 38 isn't quite recent enough for the test I want to run (besides, it would be nice for SlimerJS to run against the default version of Firefox that comes with Ubuntu these days...).

I'll see what resource://slimerjs/slimer-sdk/webpage.js is trying to do with setCSSViewport and probably submit a PR with this removal if it continues to work (I'll test it against included XULRunner 38 as well).

**Comment by DeltaReactUser** [comment] 2016-02-07 02:45
I've made a PR for this at https://github.com/laurentj/slimerjs/pull/426

It is only a quick fix because there are plenty of warnings, but it does work (so I will be using this fork for my own purposes).

**Comment by laurentj** [comment] 2016-02-13 23:13
PR merged

**Closed by laurentj** 2016-02-13 23:13 UTC
Labels: bug
