### ISSUE TITLE
how to use geolocation in slimer.js

### ISSUE THREAD

**Issue by derhuerst** [laurentj/slimerjs#464] opened 2016-04-26 19:08 UTC
I installed SlimerJS `0.9.6` by `npm i slimerjs`. I'm running OS X 10.11.4.

How do I use [the `navigator.geolocation` api](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation)?

**Comment by laurentj** [comment] 2016-04-27 10:22
duplicate of issue #86

**Closed by laurentj** 2016-04-27 10:22 UTC

**Comment by derhuerst** [comment] 2016-04-27 17:25
are you sure it's a duplicate? #86 is about a callback after permission has been granted, this is about access in general.

If there's any documentation regarding geolocation with slimer? i guess this would already solve my problem.

**Comment by laurentj** [comment] 2016-04-27 22:14
Yes, i'm sure. #86 is about a callback that return the permission. Anyway, internally, there is not any kind of permission given to the internal API called by navigator.geolocation.getCurrentPosition() or by other methods, so, it fails.
