### ISSUE TITLE
profile missing error while executing in ubuntu

### ISSUE THREAD

**Issue by ghost** [laurentj/slimerjs#291] opened 2015-01-11 22:24 UTC
When i execute the luncher in ubuntu , I get this error  : 

Your SlimerJS profile can not be loaded . It may be missing or inaccessible.

any fix to that plz.

**Comment by laurentj** [comment] 2015-01-23 16:02
No problem with ubuntu with me (I work under kubuntu).

It creates and stores profiles in /tmp/. Have you permission to create directories in /tmp/? Do you have /tmp/slimerjs.xxxx directories in it ?

What is the result of 

```bash
mktemp -d -q /tmp/slimerjs.XXXXXXXX
```

Which version of SlimerJS? standalone edition? if yes, which xulrunner/firefox do you use? Which Ubuntu version?

**Comment by JGara** [comment] 2015-02-08 12:00
Sorry for the late response . 
This error occured just once (didn't reproduce it since !).

You can close this issues . Thx .

**Closed** 2015-02-09 10:06 UTC
Labels: works for me
